#release configuration
#Mon Jun 26 10:15:11 CEST 2023
scm.commentPrefix=[maven-release-plugin] 
project.scm.de.mpg.biochem\:mars-transverseflow.connection=scm\:git\:git\://github.com/duderstadt-lab/mars-transverseflow
project.scm.de.mpg.biochem\:mars-transverseflow.developerConnection=scm\:git\:git@github.com\:duderstadt-lab/mars-transverseflow
exec.pomFileName=pom.xml
pushChanges=false
releaseStrategyId=default
scm.tag=mars-transverseflow-0.1
remoteTagging=true
project.dev.de.mpg.biochem\:mars-transverseflow=0.2-SNAPSHOT
exec.additionalArguments=-Dgpg.skip\=true 
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
projectVersionPolicyId=default
scm.url=scm\:git\:https\://github.com/duderstadt-lab/mars-transverseflow
scm.tagNameFormat=@{project.artifactId}-@{project.version}
project.scm.de.mpg.biochem\:mars-transverseflow.tag=HEAD
pinExternals=false
preparationGoals=clean verify
project.rel.de.mpg.biochem\:mars-transverseflow=0.1
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.snapshotReleasePluginAllowed=false
project.scm.de.mpg.biochem\:mars-transverseflow.url=https\://github.com/duderstadt-lab/mars-transverseflow
exec.activateProfiles=deploy-to-scijava
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
completedPhase=end-release
